#
# To be run in a folder containing all the outputs from the script
# select_putative_circular_from_split_reads.pl.
#
# The files that can be analyzed must be exclusively those generated by the script
# (tab delimited text) without any modification, not in the name, not in the format,
# not in the column order/names/.... whatever....
#
# This script will search for all the files with the pattern
# 'reads_supporting_putative_circular.xls' in their name and will analize all of them
# creating, for each of them, a new file with the same name plus '_overlaps'.
# 
# Pay attention to the strand specificity of the sequencing!

library(GenomicFeatures)

# Use TRUE for non-strand-specific sequencing
# Use FALSE for strand-specific sequencing
ignore.strand=FALSE

define.strand.mate.1 = function(x) {
  mate = x[3]
  astrand = x[7]
  if((mate == '1' & astrand == '+') | (mate == '2' & astrand == '-')) return('+')
  if((mate == '2' & astrand == '+') | (mate == '1' & astrand == '-')) return('-')
  return(NA)
}

calculate.overlaps = function(tab) {
  out = gsub('.xls','_overlaps.xls',tab)
  t = read.table(tab,head=T,sep='\t',comment.char='',quote='')
  t$mate1_strand = apply(t,1,define.strand.mate.1)
  r = GRanges(seqnames=t$achr,ranges=IRanges(start=t$abs_start,end=t$abs_end),strand=t$mate1_strand)
  t$overlaps = countOverlaps(r,r,ignore.strand=ignore.strand)
  t$overlaps = t$overlaps -1
  t = t[,c(1:28,37,36,29:35)]
  write.table(t,file=out,sep='\t',col.names=TRUE,row.names=FALSE,quote=FALSE)
}

tabs = dir(pattern='reads_supporting_putative_circular.xls')
for(i in tabs) calculate.overlaps(i)

